// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYchv2kIFUeAGJPItlfbcICfD_b-bxl-w',
    appId: '1:519800451908:web:ee6e1510d22896e0d7dd11',
    messagingSenderId: '519800451908',
    projectId: 'storybookappv2',
    authDomain: 'storybookappv2.firebaseapp.com',
    storageBucket: 'storybookappv2.firebasestorage.app',
    measurementId: 'G-13BQ4PC1PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0JqA5qXlY9kXSKKibNeeb0zR7nBgqm74',
    appId: '1:519800451908:android:e17b81d024c95215d7dd11',
    messagingSenderId: '519800451908',
    projectId: 'storybookappv2',
    storageBucket: 'storybookappv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA16cXJWkQOmPHERb0JOKbYn_e4s-oCZ5w',
    appId: '1:519800451908:ios:f4d0c653907e822dd7dd11',
    messagingSenderId: '519800451908',
    projectId: 'storybookappv2',
    storageBucket: 'storybookappv2.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA16cXJWkQOmPHERb0JOKbYn_e4s-oCZ5w',
    appId: '1:519800451908:ios:f4d0c653907e822dd7dd11',
    messagingSenderId: '519800451908',
    projectId: 'storybookappv2',
    storageBucket: 'storybookappv2.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYchv2kIFUeAGJPItlfbcICfD_b-bxl-w',
    appId: '1:519800451908:web:a3c6ac1ec8e6886fd7dd11',
    messagingSenderId: '519800451908',
    projectId: 'storybookappv2',
    authDomain: 'storybookappv2.firebaseapp.com',
    storageBucket: 'storybookappv2.firebasestorage.app',
    measurementId: 'G-E95B526B98',
  );
}
